/* This file was generated by SableCC (http://www.sablecc.org/). */

package wikiparser.node;

import wikiparser.analysis.*;

@SuppressWarnings("nls")
public final class TRBraceSeq extends Token
{
    public TRBraceSeq(String text)
    {
        setText(text);
    }

    public TRBraceSeq(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRBraceSeq(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRBraceSeq(this);
    }
}
