/* This file was generated by SableCC (http://www.sablecc.org/). */

package wikiparser.analysis;

import wikiparser.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTRBraceSeq(TRBraceSeq node);
    void caseTLBraceSeq(TLBraceSeq node);
    void caseTText(TText node);
    void caseEOF(EOF node);
}
