<?php
$patterns = array(
"like 'Cleanup\_from\_%'"
,"like 'All\_articles\_%'"
,"like 'Copy\_to\_%'"
,"like '%_articles_needing_%"
,"like '%\_pages\_needing\_%'"
,"like 'Lacking\_%'"
,"like 'All\_pages\_%'"
,"like '%\_by\_%'"
,"like '%\_in\_%'"
,"like '%\_at\_%'"
,"like '%\_stubs'"
,"like '%\_%-%'"
,"like 'A-Class%'"
,"like 'B-Class%'"
,"like 'Articles\_%'"
,"like '%\_articles'"
,"like 'Wiki_%'"
,"like '%\_of\_%'"
,"like '%\_people\_from\_%'"
,"like 'People\_from\_%'"
,"like 'Redirects\_%'"
,"like '%\_redirects'"
,"like '%\_for_deletion'"
,"like 'All\_articles\_'"
,"like 'All\_images\_'"
,"like 'All\_video\_game\_articles\_'"
,"like '%\_for\_speedy\_deletion'"
,"like '%\_navigational\_boxes'"
,"like '%\_navigational\_boxes\_%'"
,"like '%\_navbox\_templates'"
,"like '%\_Wikipedians'"
,"like '%\_templates'"
,"like 'Stubs'"
,"like 'Categories\_%'"
,"like 'Pages\_needing%'"
,"like 'Articles\_needing'"
,"like 'Candidates\_for\_%'"
,"like 'All\_images\_%'" 
,"like '%\_without\_%'" 
,"like '%\_that\_need\_%'"
,"like '%\_that\_should\_%'"
,"like '%\_add_to\_%'"
,"like '%\_Add_to\_%'"
,"like '%\_Articles_requesting\_%'"
,"like '%\_articles_requesting\_%'"
,"like '%\_Articles_requests\_%'"
,"like '%\_articles_requests\_%'"
,"like 'Category_need%'"
,"like '%\_needing%'"
,"like 'Completed_Translation%'"
,"like 'Creative_Commons%'"
,"like 'Copyright\_examinations'"
,"like 'Fair\_use\_in...\_images'"
,"like 'WikiP%'"
,"like 'Wikipedian%'"
,"like 'Image\_copyright\_tags'"
,"like 'Images\_that\_%'"
,"like '%Cleanup%'"
,"like '%\_cleanup\_%'"
,"like '%\_to\_be\_%'"
,"like '%\_lacking\_sources'"
,"like '%Articles\_from%'"
,"like '%articles\_from%'"
,"regexp '^[0-9]{1,4}\_.'"
,"regexp '^[0-9]{1,4}-[0,9]{1,4}\_'"
,"regexp '^[0-9]{1,4}-[0,9]{1,2}\_'"
,"regexp '^[0-9]{1,4}[s]\_.'"
,"like '5-a-side_football_teams'"
,"like 'ASP_World_Tour_surfers'"
,"like 'Abazins'"
,"like 'Accuracy_disputes'"
,"like 'Active_politicians'"
,"like 'Add_to_Wikisource'"
,"like 'AfD_debates'"
,"like 'Arthur_Ransome'"
,"like 'Asante'"
,"like 'Australia-centric'"
,"like 'BAA_Limited'"
,"like 'Babywearing'"
,"like 'Ballarat_Associated_Schools_(BAS)'"
,"like 'Bavaria'"
,"like 'Belarusian_Nordic_combined_skiers'"
,"like 'Benoit_Pioulard_albums'"
,"like 'Bergen_Philharmonic_Orchestra'"
,"like 'Big_Wolf_on_Campus'"
,"like 'Black_Legions_Releases'"
,"like 'Black_Legions_band'"
,"like 'Black_Legions_bootlegs'"
,"like 'Blade:_The_Series'"
,"like 'Boer_generals'"
,"like 'Bolivian_film_directors'"
,"like 'Bolivian_journalists'"
,"like 'Bolivian_poets'"
,"like 'Browser_games'"
,"like 'CASE_Tools'"
,"like 'CIS_member_countries'"
,"like 'Canterbury_Bulldogs_players'"
,"like 'Capuchin_alumni'"
,"like 'Chabad-Lubavitch_texts'"
,"like 'Children_Clubs'"
,"like 'Chinese_ski_jumpers'"
,"like 'Citizens_Alliances_for_Science'"
,"like 'Classic_American_Cars'"
,"like 'Coconut_palm_diseases'"
,"like 'Columbine_High_School_alumni'"
,"like 'Conditional_use_images'"
,"like 'Cross_country_running'"
,"like 'Cultural_education'"
,"like 'Database_theory'"
,"like 'Democratic_Party'"
,"like 'Desktop_backgrounds'"
,"like 'Directories'"
,"like 'Disambiguation'"
,"like 'Dominican_Karate'"
,"like 'EC_2.2.1'"
,"like 'East_China_Sea_countries'"
,"like 'Endangered_and_extinct_fictional_species'"
,"like 'English_natural_history_collectors'"
,"like 'Envelopes'"
,"like 'Ephraim_Kishon'"
,"like 'Equatorian_newspapers'"
,"like 'Estonian_ski_jumpers'"
,"like 'Europe-centric'"
,"like 'Evangelic_Mission_Supporters'"
,"like 'Fairy_Tail'"
,"like 'Filipino_voice_director'"
,"like 'Films_about_priests'"
,"like 'Financial_actions'"
,"like 'French_money_managers'"
,"like 'Full_House_episodes'"
,"like 'Funnel-web_spiders'"
,"like 'Future_national_leaders'"
,"like 'Ga'Hoole_locations'"
,"like 'Games_featuring_China'"
,"like 'German_natural_history_collectors'"
,"like 'Germany-centric'"
,"like 'Glass_Mask_Characters'"
,"like 'Great_Lakes_Football_Conference'"
,"like 'Greater_Metro_Conference'"
,"like 'Grizzly_Bear_albums'"
,"like 'Haberdasher's_Schools'"
,"like 'Hawaiian_musicians'"
,"like 'Heroic_acts'"
,"like 'Highlands_and_Islands_Airports'"
,"like 'History_WikiProjects'"
,"like 'How_to'"
,"like 'Hungarian_food_scientists'"
,"like 'Hymnology'"
,"like 'Hypothetical_species'"
,"like 'IQue_games'"
,"like 'Iberian_weapons'"
,"like 'Idol_series_hosts'"
,"like 'Indian_Engineering_Services'"
,"like 'Intoxication'"
,"like 'Introductions'"
,"like 'Invalid_conservation_status'"
,"like 'Isidingo_characters'"
,"like 'Israel_blogosphere'"
,"like 'Italian_American_actors'"
,"like 'Ivan_Godfrey'"
,"like 'Jandar’s_Army'"
,"like 'January_14th_Births'"
,"like 'Jeeva_Cinematographed_Films'"
,"like 'Jefferson_County,_Florida_Plantations'"
,"like 'June_26th_Births'"
,"like 'Kaizer_Chiefs_players'"
,"like 'Kitsch'"
,"like 'Kloss'"
,"like 'Landscape'"
,"like 'Leamington_Spa'"
,"like 'Lepidosirenidae'"
,"like 'Limited_geographic_scope'"
,"like 'M*A*S*H_cast_members'"
,"like 'Main_Page_alternatives'"
,"like 'Malayalam_actors'"
,"like 'Masquerade_ceremonies'"
,"like 'Massachusetts_Natural_Resources'"
,"like 'Menashe_Regional_Council'"
,"like 'Miniature_Golf'"
,"like 'Move_to_gaming_wiki'"
,"like 'Myxinidae'"
,"like 'NPOV_disputes'"
,"like 'National_Database_and_Registration_Authority'"
,"like 'Natural_bodybuilding'"
,"like 'Needs_television_infobox'"
,"like 'Neocolonization'"
,"like 'Neoliberalism'"
,"like 'New_Edition_solo_albums'"
,"like 'New_Zealand_Current_Events'"
,"like 'NiGHTS'"
,"like 'Non-standard_album_infoboxes'"
,"like 'Non-standard_holiday_infoboxes'"
,"like 'Nonce_words'"
,"like 'Northern-centric'"
,"like 'Northern_Rock_Foundation_Writers_Award_Winners'"
,"like 'Norwegian_choirs'"
,"like 'OK_Cooperative_Alliance'"
,"like 'Ohio_Players_albums'"
,"like 'Religious_radio_stations'"
,"like 'Requena-Utiel'"
,"like 'Requested_moves'"
,"like 'Requests_for_peer_review'"
,"like 'Residential_real_estate'"
,"like 'Romanian_Nordic_combined_skiers'"
,"like 'Romany_Poetry'"
,"like 'Rough_translations'"
,"like 'Russophobes'"
,"like 'Rusyn_historical_regions'"
,"like 'Rusyn_painters'"
,"like 'Rusyn_singers'"
,"like 'Saga,_Japan'"
,"like 'Salesian_alumni'"
,"like 'Sandra_songs'"
,"like 'Saskatoon_Quakers_players'"
,"like 'Scientific_Data_Systems_computers'"
,"like 'Select_Group_Referees_2006/07'"
,"like 'Self-regulatory_organizations'"
,"like 'September_17th_Births'"
,"like 'Shared_IP_addresses_from_educational_institutions'"
,"like 'Shrestha-Pradhan-Castaings_family'"
,"like 'Silicone_rubber'"
,"like 'Singers_from_Super_Girl'"
,"like 'Small_Business'"
,"like 'Snugpak'"
,"like 'Social_divisions'"
,"like 'Society_WikiProjects'" 
,"like 'Software_covers'"
,"like 'Soul_Position_albums'"
,"like 'Sound_artists'"
,"like 'South_African_art_patrons'"
,"like 'South_African_cultural_historians'"
,"like 'South_African_entomologists'"
,"like 'South_African_explorers'"
,"like 'South_African_mountaineers'"
,"like 'South_African_naturalists'"
,"like 'South_African_printmakers'"
,"like 'South_African_road_engineers'"
,"like 'South_African_taxonomists'"
,"like 'South_Coast_League'"
,"like 'South_Johor_Economic_Region'"
,"like 'South_Korean_ski_jumpers'"
,"like 'Soviet_computer_systems'"
,"like 'Spanish_Contemporary_Symphonies'"
,"like 'Speech_pathology'"
,"like 'Sports_Administrators'"
,"like 'Sports_telecast_series'"
,"like 'St_Helens_players'"
,"like 'State_Tech_Prep'"
,"like 'Stereophonic_sound'"
,"like 'Storage_systems'"
,"like 'Student_Councils'"
,"like 'Surfboard_shapers'"
,"like 'Syncretic_Faiths'"
,"like 'Tactics_games'"
,"like 'Templates_using_ParserFunctions'"
,"like 'Terms_used_to_describe_rocks'"
,"like 'Terrier_dogs'"
,"like 'The_Abingdon_Consortium'"
,"like 'The_Arrows_songs'"
,"like 'The_Emperor's_New_Groove_Franchise'"
,"like 'The_Island_Def_Jam_Music_Group_albums'"
,"like 'The_Legendary_Pink_Dots'"
,"like 'The_Man_from_Snowy_River'"
,"like 'The_Mighty_Boosh'"
,"like 'The_Mighty_Boosh_episodes'"
,"like 'The_Shadow_Children_Sequence'"
,"like 'Third_Stream_musicians'"
,"like 'Thompson_Twins'"
,"like 'Tibetan_Americans'"
,"like 'Tiverton_Town_F.C._players'"
,"like 'To_do'"
,"like 'Needs_single_infobox_conversion'"
,"like 'Needs_song_infobox_conversion'"
,"like 'To_do,_priority_undefined'"
,"like 'Tolkien_articles_with_unsourced_statements'"
,"like 'Too_Few_Viewpoints'"
,"like 'Tracey_Ullman_characters'"
,"like 'Trademarks'"
,"like 'Translation_needed'"
,"like 'Translation_requests'"
,"like 'Breton_nationalism'"
,"like 'Transpersonal_Studies'"
,"like 'Transpersonal_psychology'"
,"like 'Tucker_Family'"
,"like 'Tunisian_Public_Radios'"
,"like 'Turkish_given_names'"
,"like 'Turn-based_tactics_games'"
,"like 'Disgaea'"
,"like 'Fire_Emblem_games'"
,"like 'Front_Mission'"
,"like 'Growlanser'"
,"like 'Ogre_Battle'"
,"like 'Shining_Force'"
,"like 'Turnaround_Management'"
,"like 'UEFA_Euro_2008_player'"
,"like 'UEFA_Pro_Licence_holders'"
,"like 'UK-centric'"
,"like 'UKUSA_listening_stations'"
,"like 'UK_Raving'"
,"like 'UK_regional_academic_networks'"
,"like 'UMPC'"
,"like 'US_Presidents_from_Ohio'"
,"like 'Uhuru_Movement'"
,"like 'Unattributed_POV'"
,"like 'Uncategorized_from_April_2007'"
,"like 'Uncategorized_from_February_2007'"
,"like 'Uncategorized_from_March_2007'"
,"like 'Uncategorized_stubs_from_March_2007'"
,"like 'Uncategorized\_%'"
,"like 'Uncategorized_pages'"
,"like 'United_Arab_Emirates_Public_Universities'"
,"like 'United_Communications_Corporation'"
,"like 'United_Nations_University_faculty'"
,"like 'United_States_Merchant_Marine_Academy_Superintendents'"
,"like 'United_States_statutory_interpretation_case_law'"
,"like 'Universal_Sufism'"
,"like 'University_residences'"
,"like 'User_en'"
,"like 'User_fi'"
,"like 'User_sv'"
,"like 'Venetist_politicians'"
,"like 'Virtual_Airline'"
,"like 'Virulence_factors'"
,"like 'Vishakapatnam_Localities'"
,"like 'Vlad'"
,"like 'W.I.T.C.H.'"
,"like 'W.I.T.C.H._characters'"
,"like 'WNYW-TV'"
,"like 'WPMIXInfoboxes_requiring_completion'"
,"like 'Web_Map_Services'"
,"like 'Web_accelerators'"
,"like 'Web_server_management_software'"
,"like 'Web_service_providers'"
,"like 'Western_Pacific_Railroad_Museum'"
,"like 'Wharfedale'"
,"like 'Whitney_Independent_Study_Program_alumni'"
,"like 'Winnipeg_Warriors_players'"
,"like 'Woking_F.C._managers'"
,"like 'World_Affairs_Councils'"
,"like 'Writing_Tools'"
,"like 'Writers'_Conferences'"
,"like 'Young_Fine_Gael_Branches'"
,"like 'Young_Fine_Gael'"
,"like 'Zanzibari_Indians'"
,"like 'Ambiguous_place_names'"
,"like 'Bassists'"
,"like 'American_bassists'"
,"like 'American_rock_bassists'"
,"like 'British_bassists'"
,"like 'Canadian_rock_bassists'"
,"like 'Swedish_bassists'"
,"like 'Disambiguation_containing_homophones'"
,"like 'Former_country_articles_requiring_maintenance'"
,"like 'Ga''Hoole_locations'"
,"like 'Georgia'"
,"like 'Haberdasher''s_Schools'"
,"like 'Jazz_bassists'"
,"like 'Jazz_bass_guitarists'"
,"like 'LGBT_articles_with_unsourced_categories'"
,"like 'NPOV_disputes\_%'"
,"like 'Onsen'"
,"like 'Original_Wikipedian_userboxes'"
,"like 'Pages_over_100K'"
,"like 'PajamaNation'"
,"like 'Pearl_Jam_offshoots'"
,"like 'Performance_consulting_firms'"
,"like 'Persian_letters'"
,"like 'Petromyzontidae'"
,"like 'Philippine_student_societies_Phi_Beta_Epsilon'"
,"like 'Phractolaemidae'"
,"like 'Phrases_which_convey_a_POV'"
,"like 'Pocketbike'"
,"like 'Populist_Party_elected_officials'"
,"like 'Portraits'"
,"like 'Raphael_portraits'"
,"like 'Possible_copyright_violations'"
,"like 'Presentation_Sisters'"
,"like 'Presentation_Sisters_schools'"
,"like 'Proposed_for_deletion_for_over_five_days'"
,"like 'Protopteridae'"
,"like 'Public_Libraries'"
,"like 'Library_districts'"
,"like 'Library_districts'"
,"like 'Public_domain_images'"
,"like 'Rage_guest_programmers'"
,"like 'Randlord_wives'"
,"like 'Randlords'"
,"like 'Recently_revised'"
,"like 'Redirects'"
,"like 'Reformed_Theological_Colleges_and_Seminaries'"
,"like 'Regional_WikiProjects'"
,"like 'Sign_systems'"
,"like 'Solar-Sail_Spacecraft'"
,"like 'Solar_Sailing'"
,"like 'Stereolab'"
,"like 'Stereolab_singles'"
,"like 'Suzuka_Files'"
,"like 'The_Emperor''s_New_Groove_Franchise'"
,"like 'USA-centric'"
,"like 'Uralic'"
,"like 'WUSTL_redirect_pages'"
,"like 'Writers''_Conferences'"
,"like 'Ableton_Live_users'"
,"like 'Accounting'"
,"like 'Achaia'"
,"like 'Adobe_Flash'"
,"like 'Aerobics'"
,"like 'African_American_actors'"
,"like 'African_American_singers'"
,"like 'Agriculture_marketing_organizations'"
,"like 'Airport_infrastructure'"
,"like 'Al_Di_Meola_albums'"
,"like 'Alien_(film_series)'"
,"like 'Alien_Nation'"
,"like 'Alien_and_Predator_series'"
,"like 'Aligarh_Muslim_University'"
,"like 'Alternative_DNS_roots'"
,"like 'American_Dad!'"
,"like 'American_Idol'"
,"like 'American_Juniors'"
,"like 'American_authors'"
,"like 'American_folk_guitarists'"
,"like 'American_law'"
,"like 'American_science_fiction_writers'"
,"like 'American_soap_opera_actors'"
,"like 'American_theatre_critics'"
,"like 'Amritsar_massacre'"
,"like 'Anti-neo-Nazi_activism'"
,"like 'Applications_which_use_Growl'"
,"like 'Argentine_science_fiction_writers'"
,"like 'Art'"
,"like 'Athenians'"
,"like 'Australian_physicians'"
,"like 'Australian_politicians'"
,"like 'Australian_science_fiction_writers'"
,"like 'Australian_soap_opera_actors'"
,"like 'Australian_soccer_clubs'"
,"like 'Auto_Racing'"
,"like 'Aziza_Mustafa_Zadeh_albums'"
,"like 'BPM_albums'"
,"like 'Bands'"
,"like 'Bartending'"
,"like 'Bartending_equipment'"
,"like 'BattleTech'"
,"like 'Battles_involving_British_India'"
,"like 'BeOS_games'"
,"like 'BeOS_text_editors'"
,"like 'Beer_cocktails'"
,"like 'Belgian_science_fiction_writers'"
,"like 'Bemani_games'"
,"like 'Blake's_7'"
,"like 'Blue_Rodeo_albums'"
,"like 'Blues_guitarists'"
,"like 'Board_Games'"
,"like 'Boston'"
,"like 'Brazilian_science_fiction_writers'"
,"like 'British_East_India_Company'"
,"like 'British_East_India_Company_Army_officers'"
,"like 'British_East_India_Company_Army_soldiers'"
,"like 'British_Indian_Army_officers'"
,"like 'British_Indian_Army_regiments'"
,"like 'British_Indian_Army_soldiers'"
,"like 'British_folk_guitarists'"
,"like 'British_humorists'"
,"like 'British_physicians'"
,"like 'British_science_fiction'"
,"like 'British_science_fiction_writers'"
,"like 'British_soap_opera_actors'"
,"like 'Buffy_the_Vampire_Slayer'"
,"like 'Buildings'"
,"like 'Cameroonian_politicians'"
,"like 'Canadian_alternative_country_groups'"
,"like 'Canadian_folk_guitarists'"
,"like 'Canadian_pop_guitarists'"
,"like 'Canadian_science_fiction'"
,"like 'Canadian_science_fiction_writers'"
,"like 'Canadian_soap_opera_actors'"
,"like 'Cantonments'"
,"like 'Captain_Scarlet'"
,"like 'Cars'"
,"like 'Castlevania_games'"
,"like 'Catholic_chivalric_orders'"
,"like 'Catholic_priests'"
,"like 'Catholic_theologians'"
,"like 'Century_21_Productions'"
,"like 'Christian_rock_albums'"
,"like 'Christian_rock_genres'"
,"like 'Christian_rock_groups'"
,"like 'Civil_War'"
,"like 'Classical_guitarists'"
,"like 'Clinical_procedure_classification'"
,"like 'Cocktail_garnishes'"
,"like 'Cocktails'"
,"like 'Comics'_Greatest_World'"
,"like 'Computer_software'"
,"like 'Corb_Lund_albums'"
,"like 'Country_guitarists'"
,"like 'Cowboy_Bebop'"
,"like 'Croatian_science_fiction_writers'"
,"like 'Cuban_science_fiction_writers'"
,"like 'Czech_science_fiction_writers'"
,"like 'DH_Press'"
,"like 'DNS_software'"
,"like 'DOS_emulation_software'"
,"like 'DOS_games'"
,"like 'DOS_media_players'"
,"like 'Danish-Americans'"
,"like 'Danish_science_fiction_writers'"
,"like 'Dark_Horse_Comics_characters'"
,"like 'Dark_Horse_titles'"
,"like 'Darkover'"
,"like 'David_E._Kelley_television_programs'"
,"like 'Deprecated_shortcuts'"
,"like 'Doctor_Who'"
,"like 'Domain_hacks'"
,"like 'Domain_registrars'"
,"like 'Dread_Empire's_Fall'"
,"like 'Dune'"
,"like 'Dungeons_&_dragons'"
,"like 'Dutch_Science_fiction_writers'"
,"like 'EBay_listings'"
,"like 'Earthworm_Jim'"
,"like 'Ecuadorian_politicians'"
,"like 'Electronic_musical_groups'"
,"like 'Emerson_Drive_albums'"
,"like 'English_soap_opera_actors'"
,"like 'Exosquad'"
,"like 'F-Zero_series'"
,"like 'FX_network_shows'"
,"like 'Family_Guy'"
,"like 'Family_business'"
,"like 'Farscape'"
,"like 'Fictional_Māori'"
,"like 'Fictional_people'"
,"like 'Fictional_teachers'"
,"like 'Filename_titles_for_computer_software'"
,"like 'Finnish_science_fiction_writers'"
,"like 'Firefly_(TV_series)'"
,"like 'Flamenco_guitarists'"
,"like 'Flaming_beverages'"
,"like 'Flash_Gordon'"
,"like 'Flynn's_Taxonomy'"
,"like 'Food'"
,"like 'Foundation_universe'"
,"like 'Fox_News_Channel_shows'"
,"like 'Fox_Sports_Net_shows'"
,"like 'French_directors'"
,"like 'French_science_fiction'"
,"like 'French_science_fiction_writers'"
,"like 'Futurama'"
,"like 'GNOME'"
,"like 'GTK'"
,"like 'Galaxy_Angel'"
,"like 'Gamera_films'"
,"like 'Ganbare_Goemon_games'"
,"like 'Gay'"
,"like 'Geocodes'"
,"like 'German'"
,"like 'German_Americans'"
,"like 'German_science_fiction_writers'"
,"like 'German_soap_opera_actors'"
,"like 'Ginger_Baker's_Air_Force_albums'"
,"like 'Godzilla_films'"
,"like 'Gradius'"
,"like 'Guiding_Light_cast_members'"
,"like 'Guitar'"
,"like 'Gundam'"
,"like 'Halo'"
,"like 'Hardware_companies'"
,"like 'Haruhi_Suzumiya'"
,"like 'Harvard_alumni'"
,"like 'Heavy_metal_guitarists'"
,"like 'Herbie_Hancock_albums'"
,"like 'Hertzsprung-Russell_classifications'"
,"like 'Hitchhiker's_Guide_to_the_Galaxy'"
,"like 'Home_and_Away_cast_members'"
,"like 'Honorverse'"
,"like 'Hugo_awards'"
,"like 'Huns'"
,"like 'IBA_Official_Cocktails'"
,"like 'IRC_clients_for_Mac_OS'"
,"like 'Idioms'"
,"like 'In_Living_Color'"
,"like 'Indian-Americans'"
,"like 'Indian_Empresses'"
,"like 'Indian_National_Congress'"
,"like 'Indian_feudalism'"
,"like 'Indian_physicians'"
,"like 'Indian_revolutionaries'"
,"like 'Indian_science_fiction_writers'"
,"like 'Information_Technology'"
,"like 'Internet_Protocol'"
,"like 'Iranian'"
,"like 'Iranian-Americans'"
,"like 'Irish_abortion_providers'"
,"like 'Irish_politicians'"
,"like 'Irish_science_fiction_writers'"
,"like 'Israel_Baseball_League_managers'"
,"like 'Israeli_science_fiction_writers'"
,"like 'Israeli_swimmers'"
,"like 'Italian_science_fiction_writers'"
,"like 'Iwi_and_hapu'"
,"like 'Japanese_science_fiction_writers'"
,"like 'Jazz_guitarists'"
,"like 'Jewelry'"
,"like 'Jodoverse'"
,"like 'Jurchens'"
,"like 'Jurisprudence'"
,"like 'K.d._lang_albums'"
,"like 'Kamen_Rider'"
,"like 'Kathleen_Edwards_albums'"
,"like 'Khitans'"
,"like 'King_Kong_films'"
,"like 'Knights_Bachelor'"
,"like 'Knights_Hospitaller'"
,"like 'Knights_Templar'"
,"like 'Known_Space'"
,"like 'Ku_Klux_Klan'"
,"like 'Lensman_series'"
,"like 'Library_cataloging_and_classification'"
,"like 'Linux_BitTorrent_clients'"
,"like 'Linux_CD/DVD_writing_software'"
,"like 'Linux_CD_ripping_software'"
,"like 'Linux_Electronic_Design_Automation_clients'"
,"like 'Linux_accounting_software'"
,"like 'Linux_computer_algebra_system_software'"
,"like 'Linux_file_sharing_software'"
,"like 'Linux_games'"
,"like 'Linux_graph_plotting_software'"
,"like 'Linux_image_viewers'"
,"like 'Linux_instant_messaging_clients'"
,"like 'Linux_integrated_development_environments'"
,"like 'Linux_media_players'"
,"like 'Linux_numerical_analysis_software'"
,"like 'Linux_office_suite_software'"
,"like 'Linux_planetarium_software'"
,"like 'Linux_security_software'"
,"like 'Linux_vector_graphics_software'"
,"like 'Living_People'"
,"like 'Livonian_Order'"
,"like 'Londoners_(Ontario)'"
,"like 'Los_Angeles'"
,"like 'Luther_Wright_and_the_Wrongs_albums'"
,"like 'Luxembourgish_science_fiction_writers'"
,"like 'Légion_d'honneur_recipients'"
,"like 'MADtv'"
,"like 'MTV'"
,"like 'Mac_OS_X_CD_ripping_software'"
,"like 'Mac_OS_X_IRC_clients'"
,"like 'Mac_OS_X_emulation_software'"
,"like 'Mac_OS_X_games'"
,"like 'Mac_OS_X_instant_messengers'"
,"like 'Mac_OS_X_media_players'"
,"like 'Mac_OS_X_text_editors'"
,"like 'Mac_OS_X_web_browsers'"
,"like 'Mac_OS_X_word_processors'"
,"like 'Mac_OS_emulation_software'"
,"like 'Mac_OS_games'"
,"like 'Mac_OS_instant_messaging_clients'"
,"like 'Mac_OS_media_players'"
,"like 'Mac_OS_text_editors'"
,"like 'Mac_OS_web_browsers'"
,"like 'Mac_OS_word_processors'"
,"like 'Mac_software_companies'"
,"like 'Macross'"
,"like 'Mahavishnu_Orchestra_albums'"
,"like 'Major_League_Baseball_pitchers_who_have_pitched_a_perfect_game'"
,"like 'Martian_Successor_Nadesico'"
,"like 'Marvel_Comics_supervillain_teams'"
,"like 'Matrix_series'"
,"like 'Medeski_Martin_&_Wood_albums'"
,"like 'Mega_Man'"
,"like 'Metal_Gear_games'"
,"like 'Metroid'"
,"like 'Metroid_games'"
,"like 'Midway_games'"
,"like 'Midwifery'"
,"like 'Military_Cross_recipients'"
,"like 'Military_orders'"
,"like 'Mixed_drink_shooters_and_drink_shots'"
,"like 'Monarchomachs'"
,"like 'Mongol_Khans'"
,"like 'Moriori'"
,"like 'Mormons'"
,"like 'Mothra_films'"
,"like 'Muhammad_Ali_Jinnah'"
,"like 'Mushrooms'"
,"like 'Music_lists'"
,"like 'Muslim_League'"
,"like 'Māori_art'"
,"like 'Māori_culture'"
,"like 'Māori_gods'"
,"like 'Māori_politics'"
,"like 'Māori_words_and_phrases'"
,"like 'Native_Americans'"
,"like 'Nebulous'"
,"like 'Neighbours_cast_members'"
,"like 'Neo-Nazi_movements_and_concepts'"
,"like 'Neo-Nazi_music'"
,"like 'Neo-Nazi_organizations'"
,"like 'Neo-Nazi_political_parties'"
,"like 'Neo-Nazi_publications'"
,"like 'Neo-Nazi_websites'"
,"like 'Neo-Nazis'"
,"like 'Neo-noir'"
,"like 'New_Zealand_Māori_people'"
,"like 'New_Zealand_land_wars'"
,"like 'New_Zealand_science_fiction_writers'"
,"like 'No-Man_albums'"
,"like 'Non-alcoholic_mixed_drinks'"
,"like 'Nonfiction_books'"
,"like 'Noon_Universe'"
,"like 'Noon_Universe_novels'"
,"like 'Non-article_anime_and_manga_pages'"
,"like 'Norwegian_science_fiction_writers'"
,"like 'Nursing_organizations'"
,"like 'Open_Source'"
,"like 'Open_source'"
,"like 'Operation_Deadlight'"
,"like 'PC_Games'"
,"like 'Pakistan_movement_activists'"
,"like 'Parisians'"
,"like 'Parodius'"
,"like 'Passions_cast_members'"
,"like 'Pat_Metheny_albums'"
,"like 'Patent_classifications'"
,"like 'People_associated_with_the_British_East_India_Company'"
,"like 'Pierre_Moerlen's_Gong_albums'"
,"like 'Pilots'"
,"like 'Playstation_3_games'"
,"like 'Polish_folk_guitarists'"
,"like 'Polish_science_fiction_writers'"
,"like 'Popular_education'"
,"like 'Port_Charles_cast_members'"
,"like 'Portuguese_science_fiction_writers'"
,"like 'Predator_series'"
,"like 'Prisoner_cast_members'"
,"like 'Professors'"
,"like 'Programming_tools'"
,"like 'Protestants'"
,"like 'Puerto_Rican_soap_opera_actors'"
,"like 'Puerto_Rican_swimmers'"
,"like 'Punk_rock_guitarists'"
,"like 'R_(programming_language)'"
,"like 'Racing_games'"
,"like 'Railways'"
,"like 'Rap_albums'"
,"like 'Retail'"
,"like 'Return_to_Forever_albums'"
,"like 'Revelation_Space'"
,"like 'Revolutionary_movement_for_Indian_independence'"
,"like 'Rhythm_and_blues_guitarists'"
,"like 'RoboCop'"
,"like 'Robotech'"
,"like 'Rock_guitarists'"
,"like 'Rock_mass_classifications'"
,"like 'Roman_Catholicism'"
,"like 'Romanian_science_fiction_writers'"
,"like 'Rumble_Roses_games'"
,"like 'Russian_Americans'"
,"like 'Russian_science_fiction_novels'"
,"like 'Russian_science_fiction_writers'"
,"like 'SVGAlib_programs'"
,"like 'School'"
,"like 'School_fires'"
,"like 'School_massacres'"
,"like 'Science_fiction'"
,"like 'Science_fiction_academics'"
,"like 'Science_fiction_anime'"
,"like 'Science_fiction_artists'"
,"like 'Science_fiction_awards'"
,"like 'Science_fiction_book_series'"
,"like 'Science_fiction_books'"
,"like 'Science_fiction_characters'"
,"like 'Science_fiction_comics'"
,"like 'Science_fiction_concepts'"
,"like 'Science_fiction_conventions'"
,"like 'Science_fiction_critics'"
,"like 'Science_fiction_culture'"
,"like 'Science_fiction_editors'"
,"like 'Science_fiction_fandom'"
,"like 'Science_fiction_fans'"
,"like 'Science_fiction_fanzines'"
,"like 'Science_fiction_films'"
,"like 'Science_fiction_games'"
,"like 'Science_fiction_genres'"
,"like 'Science_fiction_literature'"
,"like 'Science_fiction_manga'"
,"like 'Science_fiction_music'"
,"like 'Science_fiction_podcasts'"
,"like 'Science_fiction_radio_programs'"
,"like 'Science_fiction_related_magazines'"
,"like 'Science_fiction_television'"
,"like 'Science_fiction_television_series'"
,"like 'Science_fiction_theatre'"
,"like 'Science_fiction_themes'"
,"like 'Science_fiction_translators'"
,"like 'Science_fiction_websites'"
,"like 'Science_fiction_writers'"
,"like 'Scottish_Americans'"
,"like 'Scottish_soap_opera_actors'"
,"like 'Second-level_domains'"
,"like 'Serbian_science_fiction_writers'"
,"like 'Shania_Twain_albums'"
,"like 'Shopping_centers'"
,"like 'Shortland_Street_cast_members'"
,"like 'Silent_Hill'"
,"like 'Singer'"
,"like 'Slovenian_science_fiction_writers'"
,"like 'So_You_Think_You_Can_Dance'"
,"like 'Soap_Opera_Digest_Award_winners'"
,"like 'Soccer'"
,"like 'Soft_Machine_albums'"
,"like 'Sonic_the_Hedgehog'"
,"like 'Sound_engineers'"
,"like 'South_African_soap_opera_actors'"
,"like 'Soviet_science_fiction'"
,"like 'Space:_1999'"
,"like 'Space:_Above_and_Beyond'"
,"like 'Space_Battleship_Yamato'"
,"like 'Spanish_architecture'"
,"like 'Spanish_science_fiction_writers'"
,"like 'Sport'"
,"like 'Sportscasters'"
,"like 'StarCraft'"
,"like 'Star_Control'"
,"like 'Star_Fox'"
,"like 'Star_Trek'"
,"like 'Star_Trek_rank_insignia'"
,"like 'Star_Wars'"
,"like 'Starcraft'"
,"like 'Stargate'"
,"like 'Starship_Troopers'"
,"like 'Stones_Throw_albums'"
,"like 'Stuntmen'"
,"like 'Super_Nintendo_games'"
,"like 'Swedish_pop_guitarists'"
,"like 'Swedish_science_fiction_writers'"
,"like 'Swiss_science_fiction_writers'"
,"like 'Tai_history'"
,"like 'Tanguts'"
,"like 'Telenovela_actors'"
,"like 'Teutonic_Knights'"
,"like 'Texas_cast_members'"
,"like 'Thai_science_fiction_writers'"
,"like 'The_Beano'"
,"like 'The_Colbys_cast_members'"
,"like 'The_Culture'"
,"like 'The_Journeyman_Project'"
,"like 'The_Netherlands'"
,"like 'The_Restless_Years_cast_members'"
,"like 'The_Simpsons'"
,"like 'The_Tick'"
,"like 'The_Time_Machine'"
,"like 'The_Young_Doctors_cast_members'"
,"like 'The_Young_and_the_Restless_cast_members'"
,"like 'Theater'"
,"like 'Thunderbirds'"
,"like 'Tocharians'"
,"like 'Top-level_domains'"
,"like 'Traffic_albums'"
,"like 'Transformers'"
,"like 'Transport'"
,"like 'Travancore'"
,"like 'Traveller'"
,"like 'Tribal_Tech_albums'"
,"like 'Tron'"
,"like 'Twinbee_games'"
,"like 'U-boat_accidents'"
,"like 'U-boat_commanders'"
,"like 'U-boat_flotillas'"
,"like 'UNESCO_Nomenclature'"
,"like 'Ukrainian_science_fiction_writers'"
,"like 'Underground_hip_hop_musicians'"
,"like 'United_Kingdom_law_firms'"
,"like 'United_States_Congress'"
,"like 'United_States_musical_groups'"
,"like 'Universities'"
,"like 'Uralic_mythology'"
,"like 'Estonian_mythology'"
,"like 'Finnish_paganism'"
,"like 'Hungarian_mythology'"
,"like 'Ugrian_mythology'" 
,"like 'Video_game_content_ratings_systems'"
,"like 'Virtual_communities'"
,"like 'Virtual_reality_communities'"
,"like 'Virtual_reality_pioneers'"
,"like 'Virus'"
,"like 'Visual_Arts'"
,"like 'Vorkosigan_Saga'"
,"like 'WarCraft'"
,"like 'Warhammer_40,000'"
,"like 'Washington_University_alumni'"
,"like 'Weather_Report_albums'"
,"like 'Welsh_soap_opera_actors'"
,"like 'Wine_cocktails'"
,"like 'Wing_Commander'"
,"like 'Winnipeggers'"
,"like 'WPTR/current/Top/inprocess'"
,"like 'Xiongnu'"
,"like 'Youth_organisations'"
,"like 'Copied_and_pasted_articles_and_sections'"
,"like 'Ob-Ugrian_gods'"
);


$replaceMentArray=array();
$replaceMentArray[0][0]='http://dbpedia.org/property/'."bornInYear";
$replaceMentArray[0][1]="http://www.w3.org/2001/XMLSchema#gYear";
$replaceMentArray[0][2]="_births";
$replaceMentArray[0][3]=0;
$replaceMentArray[1][0]='http://dbpedia.org/property/'."diedInYear";
$replaceMentArray[1][1]="http://www.w3.org/2001/XMLSchema#gYear";
$replaceMentArray[1][2]="_deaths";
$replaceMentArray[1][3]=0;
$replaceMentArray[2][0]='http://dbpedia.org/property/'."producedInYear";
$replaceMentArray[2][1]="http://www.w3.org/2001/XMLSchema#gYear";
$replaceMentArray[2][2]="_films";
$replaceMentArray[2][3]=0;
$replaceMentArray[3][0]='http://dbpedia.org/property/'."writtenInYear";
$replaceMentArray[3][1]="http://www.w3.org/2001/XMLSchema#gYear";
$replaceMentArray[3][2]="_books";
$replaceMentArray[3][3]=0;
$replaceMentArray[4][0]='http://dbpedia.org/property/'."happenedInYear";
$replaceMentArray[4][1]="http://www.w3.org/2001/XMLSchema#gYear";
$replaceMentArray[4][2]="_disasters"; 
$replaceMentArray[4][3]=0;



$whitelist=array("Science", "People", "Research", "Library_and_information_science",
"Arts", "Culture", "Humanities", "Cultural_movements", "Celebrities", "Classics", "Cooking", "Critical_theory",
"Entertainment", "Food_and_drink", "Games", "Languages", "Literature","Auto_racing","Mass_media", "Mythology", "Parapsychology","Science_fiction","Categories_by_continent",
"Parties", "Pets", "Philosophy", "Popular_culture", "Publications", "Radio", "Television", "Traditions", "Tourism",
"Toys", "Arts and crafts", "Festivals", "Hobbies", "Humor", "Literature", "Museums", "Poetry", "Performing_arts",
"Dance", "Film", "Music", "Opera", "Theatre", "Visual_arts","Board_games", "Architecture", "Crafts", "Design", "Drawing", 
"Film_(Animation)", "Comics", "Painting", "Photography", "Sculpture",  "Chess", "Go", "Card_games",
"Magic:_The_Gathering", "Poker", "Video_games", "Final_Fantasy", "Nintendo", "Pokémon", "RuneScape", "StarCraft",
"Warcraft", "Role-playing_games", "Sports", "American_football", "Baseball",
"Basketball", "Cricket", "Cycling", "Football", "Golf", "Ice_hockey", "Lacrosse", "Olympics", "Rugby", "Swimming",
"Tennis", "Newspapers", "Publications", "Publishing", "Radio", "Television", "Geography", "Climate", "Continents", 
"Countries", "Landforms", "Maps", "Parks", "Subterranea", "Towns", "Villages", "Health", "fitness", "Self-care",
"Health_science", "Determinants_of_health", "Health_promotion", "Life_extension", "Prevention", "Nutrition", 
"Dietary_supplements", "Nutrients", "Amino_acids", "Minerals", "Nootropics", "Phytochemicals", "Vitamins", 
"Nutritional_advice_pyramids", "Exercise", "Bodyweight_exercise_(Calisthenics)", "Exercise_equipment",
"Exercise_instructors", "Dancing", "Exercise_physiology", "Hiking", "Pilates", "Running", "T'ai Chi Ch'uan", 
"Walking", "Weight_training", "Weight_training_exercises", "Yoga", "Hygiene", "Cleaning", "Oral_hygiene", 
"Sleep_hygiene", "Occupational_hygiene", "Positive_mental_attitude", "Mental_health", "Positive_psychology", 
"Epidemiology", "Midwifery", "Nursing", "Optometry", "Pharmacy", "Public_health", "Specialties", "Medicine", 
"Veterinary_medicine", "Dentistry", "Dental_hygiene", "Orthodontics", "Dental_hygiene_and_Orthodontics", 
"Human_medicine", "Cardiology", "Endocrinology", "Forensics", "Geriatrics", "Hematology", "Nephrology", "Neurology",
"Neurosurgery", "Orthopedic_surgery", "Pathology", "Pediatrics", "Psychiatry", "Anti-psychiatry", "Rheumatology",
"Surgery", "Urology", "History", "Events", "History_by_Period", "History_by_Topic", "History_of_science", 
"Historiography", "Timelines", "History_by_Region", "History_by_continent", "History_of_Africa", "History_of_Asia",
"History_of_Euroasia", "History_of_Europe","History_of_North_America", "History_of_Oceania", "History_of_South America",
"History_by_country", "Mathematics", "Abstraction", "Algebra", "Analysis", "Arithmetic", "Education", "Equations", 
"Geometry", "Logic", "Measurement", "Numbers", "Proofs", "Statistics", "Theorems", "Trigonometry", "Natural_sciences",
"Nature", "Scientific_method", "Protoscience", "Scientists", "Biology", "Ecology", "Health_sciences", "Medicine",
"Physical_sciences", "Astronomy", "Chemistry", "Earth_sciences", "Physics", "Space", "Personal_life", "Self_and_Surnames",
"Beginners_and_newcomers", "Biographies", "Children", "Heads_of_state", "Humans", "Legal_categories_of_people",
"Men", "Old_age", "Political_people", "Rivalry", "Social_groups", "Subcultures", "Women", "Activists", "Actors",
"Astronauts", "Billionaires", "Chief_executives", "Colonial_people","Composers", "Cyborgs", "Defectors", 
"Entrepreneurs", "Generals", "Humanitarians", "Innovators", "Inventors", "Legal_people", "Lesbian",  
"bisexual_or_transgendered", "Monarchs", "Musicians", "Musical_groups", "Philosophers", "Politicians", "Presidents",
"Princes", "Revolutionaries", "Scientists", "Settlers", "Slaves", "Victims", "People_associated_with_war",
"World_record_holders", "Writers", "Alter_egos", "Consciousness_studies", "Gender", "Personality", "Phrenology",
"Sexuality", "Sexual_orientation_and_identity", "Clothing", "Employment", "Home", "Income", "Interpersonal_relationships",
"Leisure", "Love", "Motivation", "Personal_development", "Philosophy", "Thought", "Philosophy", "Branches",
"Movements", "Schools_and_traditions", "Theories", "Arguments", "Philosophers", "Literature", "Aesthetics",
"Epistemology", "Ethics", "Metaphysics", "Thinking_and_thinking_skills", "Attention", "Cognition", 
"Cognitive_biases", "Creativity", "Decision_theory", "Emotion", "Error", "Imagination", "Intelligence",
"Intelligence_researchers", "Learning", "Memory", "Memory_biases", "Mnemonics", "Nootropics_(smart_drugs)",
"Organizational_thinking", "Perception", "Problem_solving", "Psychological_adjustment", "Psychometrics", 
"Qualities of thought", "Religion", "Belief", "Allah", "Ayya_Vaikundar", "Bible", "Buddhas", "Deities", 
"Demons", "Exorcism", "God", "Jesus", "Mythology", "Occult", "Prayer", "Prophecy", "Qur'an", "Religious_ethics", 
"Religious_faiths,_traditions,_and_movements", "Religious_law", "Religious_philosophy_and_doctrine", "Ritual",
"Spirituality", "Theology", "Triune_gods", "Virtue", "Belief_systems", "Agnosticism", "Animism", "Atheism",
"Deism", "Determinism", "Esotericism", "Gnosticism", "Humanism", "Monism", "Monotheism", "Mysticism", "New_Age",
"Paganism", "Pantheism", "Polytheism", "Skepticism", "Spiritualism", "Transcendentalism", "Unitarianism", 
"Major_beliefs_of_the_world", "Agnosticism", "Atheism", "Ayyavazhi", "Bahá'í_Faith", "Buddhism", "Cao_Dai", 
"Chinese_traditional_religion", "Christianity", "Confucianism", "Diasporas", "Falun_Gong", "Hinduism", "Islam",
"Neopaganism", "Jainism", "Judaism", "Rastafarianism", "Scientology", "Sikhism", "Spiritism", "Shinto", "Taoism",
"Tenrikyo", "Unitarian_Universalism", "Zoroastrianism", "Mythology", "Abrahamic_mythology", "Ayyavazhi_mythology",
"Christian_mythology", "Hindu_mythology", "Jewish_mythology", "Satanism", "Criticism_of_religion", "Social_sciences_and_society", "gay",
"Social_sciences", "Society", "Scientific_method", "Protoscience", "Scientists", "Anthropology", "Archaeology",
"Cultural_studies", "Demographics", "Economics", "Heuristics", "Information_studies", "International_relations", 
"Linguistics", "Psychology", "Media_studies", "Political_science", "Social_scientists", "Sociology", "Sexology",
"Systems_theory", "Society", "Business", "Communication", "Education", "Ethnic_groups", "Family", "Finance", 
"Government", "Industries", "Infrastructure", "Labor", "Law", "Money", "Organizations", "Politics", "War", 
"Technology", "Applied_sciences", "Aeronautics", "Agriculture_&_agronomy", "Architecture", "Artificial_intelligence",
"Automation", "Automobiles", "Aviation", "Big_Science", "Biotechnology", "Cartography", "Civil_engineering",
"Chemical_engineering", "Communication", "Computer_science", "Computing", "Programming", "Software_engineering", 
"Unsolved_problems_in_computer_science", "Unsolved_problems_in_software_engineering", "Construction", "Dentistry",
"Design", "Education", "Electronics", "Energy", "Engineering", "Ergonomics", "Firefighting", "Forensics", "Forestry",
"Free_software", "Industry", "Information_science", "Information_technology", "Internet", "Library_and_information_science",
"Management", "Manufacturing", "Marketing", "Mass_communication", "Mechanical_engineering", "Unsolved_problems_in_neuroscience",
"Military", "Military_science", "Mining", "Nanotechnology", "Nuclear_technology", "Robotics", "Space_exploration",
"Structural_engineering", "Technology_forecasting", "Telecommunications", "Tools", "Transportation", "Vehicles"
,"States_of_Germany","Fundamental","Named_categories","Portals","Retrograde_categories"
);


$tempTableName="temp_cats";
$tempTableType="MyISAM";
// $tempTableType="Heap";

// settings for dbDestination target database, insert your setting below
$sqlDestHost="";
$sqlDestUser="";
$sqlDestPwd="";
$sqlDestDb="";
$tableName="";



