<?php
$GLOBALS['MEDIAWIKI_NAMESPACES'] = array(
    'legal' => array(MW_CATEGORY_NAMESPACE, MW_TEMPLATE_NAMESPACE, MW_FILE_NAMESPACE, MW_FILEALTERNATIVE_NAMESPACE),
    'en' => array(MW_CATEGORY_NAMESPACE => 'Category', MW_TEMPLATE_NAMESPACE=>'Template', MW_FILE_NAMESPACE=>'File', MW_FILEALTERNATIVE_NAMESPACE=>'Image'),
    'de' => array(MW_CATEGORY_NAMESPACE => 'Kategorie', MW_TEMPLATE_NAMESPACE=>'Template', MW_FILE_NAMESPACE=>'Datei', MW_FILEALTERNATIVE_NAMESPACE=>'Bild'),
    'ko' => array(MW_CATEGORY_NAMESPACE => '분류', MW_TEMPLATE_NAMESPACE=>'틀', MW_FILE_NAMESPACE=>'파일', MW_FILEALTERNATIVE_NAMESPACE=>'파일')
);
